# Auto-generated from config/theme.DEBUG_THEME
from pydantic import BaseModel, ConfigDict


class ThemeSchema(BaseModel):
    font_family: str
    heading_font_family: str
    font_size: int
    font_weight: int
    title_font_weight: int
    title_font_size: int
    balance_font_weight: int
    balance_font_size: int
    pnl_font_weight: int
    pnl_font_size: int
    ui_font_weight: int
    ui_font_size: int
    pill_font_weight: int
    pill_font_size: int
    investing_font_size: int
    investing_font_weight: int
    badge_font_size: int
    badge_font_weight: int
    metric_cell_width: int
    metric_cell_height: int
    chip_height: int
    pill_radius: int
    badge_height: int
    badge_radius: int
    badge_width: int
    badge_gap: int
    glow_blur_radius: int
    glow_offset_x: int
    glow_offset_y: int
    gap_sm: int
    gap_md: int
    gap_lg: int
    card_radius: int
    graph_border_width: int
    panel_radius: int
    badge_live_bg: str
    badge_live_fg: str
    badge_sim_bg: str
    badge_sim_fg: str
    badge_border_radius: int
    ENABLE_GLOW: bool
    ENABLE_HOVER_ANIMATIONS: bool
    ENABLE_TOOLTIP_FADE: bool
    TOOLTIP_AUTO_HIDE_MS: int
    live_dot_pulse_ms: int
    perf_safe: bool
    ink: str
    subtle_ink: str
    fg_primary: str
    fg_muted: str
    text_primary: str
    text_dim: str
    bg_primary: str
    bg_secondary: str
    bg_panel: str
    bg_elevated: str
    card_bg: str
    border: str
    cell_border: str
    accent: str
    accent_warning: str
    accent_alert: str
    conn_status_green: str
    conn_status_yellow: str
    conn_status_red: str
    pill_text_active_color: str
    live_dot_fill: str
    live_dot_border: str
    mode_badge_color: str
    mode_badge_radius: int
    mode_badge_font_weight: int
    mode_badge_font_size: int
    pnl_pos_color: str
    pnl_neg_color: str
    pnl_neu_color: str
    pnl_pos_color_weak: str
    pnl_neg_color_weak: str
    pnl_neu_color_weak: str
    flash_pos_color: str
    flash_neg_color: str
    flash_neu_color: str
    sharpe_track_pen: str
    sharpe_track_bg: str
    grid_color: str
    investing_text_color: str
    badge_bg_color: str
    badge_border_color: str
    badge_text_color: str
    glow_color: str

    model_config = ConfigDict(extra="forbid")
