#!/usr/bin/env python3
# -------------------- [Sync Theme Schema with JSON Report] (start)
"""
Sync Theme Schema (Enhanced)
----------------------------
Generates `config/theme_schema.py` automatically from the active THEME
dictionaries (LIVE, SIM, DEBUG). Also supports JSON audit reports.

Usage:
    python tools/sync_theme_schema.py
    python tools/sync_theme_schema.py --force
    python tools/sync_theme_schema.py --report theme_audit.json

Flags:
    --force    Overwrite existing schema without confirmation
    --report   Output JSON report of theme key/type inconsistencies
"""

from __future__ import annotations

from datetime import datetime
import difflib
import importlib
import json
from pathlib import Path
import sys
from typing import Any, Dict


# Import shared validation utilities
try:
    from tools.theme_validation import infer_type, validate_theme_keys
except ImportError:
    from theme_validation import infer_type, validate_theme_keys

__scope__ = "maintenance.sync_theme_schema"

# --------------------------------------------------------------------
# Load current THEME definitions
# --------------------------------------------------------------------
try:
    theme_mod = importlib.import_module("config.theme")
except Exception as e:
    print(f" Failed to import config.theme: {e}")
    sys.exit(1)

THEMES: dict[str, dict[str, Any]] = {
    name: getattr(theme_mod, name) for name in ("DEBUG_THEME", "SIM_THEME", "LIVE_THEME") if hasattr(theme_mod, name)
}
if not THEMES:
    print(" No THEME dictionaries found in config.theme.")
    sys.exit(1)


# --------------------------------------------------------------------
# Validation (using shared utilities from theme_validation.py)
# --------------------------------------------------------------------
def print_validation_report(report: dict) -> None:
    """Print human-readable validation report."""
    print(" Validating theme key consistency...\n")

    consistent = report["summary"] == "All themes consistent"

    for name, details in report["themes"].items():
        missing = details.get("missing_keys", [])
        extra = details.get("extra_keys", [])
        type_mismatches = details.get("type_mismatches", {})
        invalid_colors = details.get("invalid_colors", {})

        if missing or extra:
            print(f" Inconsistency detected in {name}:")
            if missing:
                print(f"  Missing keys: {missing}")
            if extra:
                print(f"  Extra keys: {extra}")
            print()

        if type_mismatches:
            print(f" Type mismatches in {name}: {type_mismatches}\n")

        if invalid_colors:
            print(f" Invalid color formats in {name}: {invalid_colors}\n")

    print(
        " All theme dictionaries share identical key sets.\n" if consistent else " Key/type mismatches detected.\n"
    )


# --------------------------------------------------------------------
# Main validation
# --------------------------------------------------------------------
report = validate_theme_keys(THEMES)
print_validation_report(report)

# Optional JSON report output
if "--report" in sys.argv:
    idx = sys.argv.index("--report")
    try:
        out_file = Path(sys.argv[idx + 1])
    except IndexError:
        print(" Missing filename after --report flag.")
        sys.exit(1)
    out_file.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(f" Wrote JSON audit report → {out_file.resolve()}\n")

# --------------------------------------------------------------------
# Schema generation
# --------------------------------------------------------------------
ref_theme = THEMES.get("LIVE_THEME") or next(iter(THEMES.values()))
fields = [f"    {k}: {infer_type(v)}" for k, v in ref_theme.items()]
schema_text = f"""# Auto-generated by sync_theme_schema.py
# Generated on {datetime.now():%Y-%m-%d %H:%M:%S}
# Do not edit manually; changes will be overwritten.

from pydantic import BaseModel, ConfigDict

class ThemeSchema(BaseModel):
{chr(10).join(fields)}

    model_config = ConfigDict(extra='forbid')
"""
schema_path = Path("config/theme_schema.py")

# Diff preview
if schema_path.exists():
    old = schema_path.read_text(encoding="utf-8")
    diff = list(
        difflib.unified_diff(old.splitlines(), schema_text.splitlines(), fromfile="old", tofile="new", lineterm="")
    )
    if diff:
        print(" Diff preview:")
        print("\n".join(diff[:20]))
        if len(diff) > 20:
            print("... (truncated)")
    else:
        print("No differences detected (schema already up to date).")

# Overwrite confirmation
if schema_path.exists() and "--force" not in sys.argv:
    confirm = input("\nOverwrite existing theme_schema.py? [y/N]: ").lower()
    if confirm != "y":
        print("Aborted.")
        sys.exit(0)

schema_path.write_text(schema_text, encoding="utf-8")
print(f"\n Wrote {schema_path} ({len(ref_theme)} fields)\n")
# -------------------- [Sync Theme Schema with JSON Report] (end)
